# Generated by Django 2.2.1 on 2019-11-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0002_auto_20191110_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='tweetdata',
            name='tweet_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
